Tab looping example using qicharts2 data
nhs-r-community/demos-and-how-tos pull request #20
Opened 2021-11-24 18:08 UTC by Lextuga007

Can the GitHub pages be switched on to show the rendered html examples? It's not set so just checking that would be ok.

2021-11-24 18:38 UTC, ChrisBeeley requested changes
Thanks for the PR!

I think it would be better in a separate folder. The loop_rmarkdown folder already has a few things in it. If you particularly want to keep them together it would be better IMO to use the same palmerpenguins example (optional) and also to update the README in the folder to describe what all the files do

2021-11-24 18:44 UTC, ChrisBeeley commented
I turned on GitHub pages, but it's currently set to main so the HTML is not visible on main yet

2021-11-25 09:55 UTC, Lextuga007 commented
I've moved this to a separate folder - apologies, I should have done that before! 

I've not changed the example as I specifically wanted to use healthcare data and this relates to a nice vignette that corresponds to it. I've also used it as an example in a blog 😄 Ideally we should be using NHSR packages like the NHSRdatasets 😉

2021-11-26 13:29 UTC, ChrisBeeley approved these changes

2021-11-26 13:29 UTC, merged